#!/bin/sh  
#memcached auto-start   
#  
# description: Auto-starts memcached  
# processname: memcached  
# pidfile: /var/memcached.pid   
 
mkdir war

cd war

cp ../ep-www/target/ROOT.war ./

cp ../ep-company/target/company.war ./

cp ../ep-news/target/news.war ./

cp ../ep-trade/target/trade.war ./

cp ../ep-esite/target/esite.war ./

cp ../ep-exhibit/target/exhibit.war ./
cp ../ep-myesite/target/myesite.war ./

exit 0
