<%@ Page Language="C#" MasterPageFile="~/admin/admin1.master" AutoEventWireup="true" CodeFile="PingServices.aspx.cs" Inherits="admin_Pages_PingServices" Title="Ping 服务" %>
<asp:Content ID="Content1" ContentPlaceHolderID="cphAdmin" Runat="Server">

<div id="Div1" class="settings" style="background-color:#FFFFDD;" runat="server">
<h1>说明与使用提示</h1>
博易支持 Ping 服务，这项功能能够帮助您发表文章时自动通知外界（搜索引擎等服务），以便让您的文章在发布之后尽可能快速地被关注。<br />
以下是 Ping 服务项目列表，每一条记录就是一项 Ping 服务，您可以收集适合您的 Ping 服务加入其中。
</div>

  <asp:TextBox runat="Server" ID="txtNewCategory" Width="300" MaxLength="255" />  
  <asp:Button runat="server" ID="btnAdd" ValidationGroup="new" />
  <asp:RequiredFieldValidator ID="RequiredFieldValidator1" runat="Server" ValidationGroup="new" ControlToValidate="txtNewCategory" ErrorMessage="请指定一个 Ping 服务" /><br /><br /><hr />

  <asp:GridView runat="server" ID="grid" CssClass="category"  
    UseAccessibleHeader="true" 
    GridLines="None"
    AutoGenerateColumns="false" 
    AlternatingRowStyle-CssClass="alt" 
    AutoGenerateDeleteButton="true" 
    AutoGenerateEditButton="true">
    <Columns>      
      <asp:TemplateField HeaderText="<%$ Resources:labels, name %>">
        <ItemTemplate>
          <%# Eval("value") %>
        </ItemTemplate>
        <EditItemTemplate>
          <asp:TextBox runat="server" ID="txtName" Width="100%" MaxLength="255" Text='<%# Eval("value") %>' />
        </EditItemTemplate>
      </asp:TemplateField>
    </Columns>
  </asp:GridView>
</asp:Content>

