package com.zz91.ep.domain.crm;

import java.util.Date;

/**
 * CrmCs generated by MyEclipse Persistence Tools
 */

public class CrmCs implements java.io.Serializable {

	// Fields

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private String csAccount;
	private Integer cid;
	private Date gmtVisit;
	private Date gmtNextVisitPhone;
	private Date gmtNextVisitEmail;
	private String visitTarget;
	private Date gmtCreated;
	private Date gmtModified;

	// Constructors

	/** default constructor */
	public CrmCs() {
	}

	/** minimal constructor */
	public CrmCs(Integer id, String csAccount, Integer cid, Date gmtVisit,
			Date gmtCreated, Date gmtModified) {
		this.id = id;
		this.csAccount = csAccount;
		this.cid = cid;
		this.gmtVisit = gmtVisit;
		this.gmtCreated = gmtCreated;
		this.gmtModified = gmtModified;
	}

	/** full constructor */
	public CrmCs(Integer id, String csAccount, Integer cid, Date gmtVisit,
			Date gmtNextVisitPhone, Date gmtNextVisitEmail, String visitTarget,
			Date gmtCreated, Date gmtModified) {
		this.id = id;
		this.csAccount = csAccount;
		this.cid = cid;
		this.gmtVisit = gmtVisit;
		this.gmtNextVisitPhone = gmtNextVisitPhone;
		this.gmtNextVisitEmail = gmtNextVisitEmail;
		this.visitTarget = visitTarget;
		this.gmtCreated = gmtCreated;
		this.gmtModified = gmtModified;
	}

	// Property accessors

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getCsAccount() {
		return this.csAccount;
	}

	public void setCsAccount(String csAccount) {
		this.csAccount = csAccount;
	}

	public Integer getCid() {
		return this.cid;
	}

	public void setCid(Integer cid) {
		this.cid = cid;
	}

	public Date getGmtVisit() {
		return this.gmtVisit;
	}

	public void setGmtVisit(Date gmtVisit) {
		this.gmtVisit = gmtVisit;
	}

	public Date getGmtNextVisitPhone() {
		return this.gmtNextVisitPhone;
	}

	public void setGmtNextVisitPhone(Date gmtNextVisitPhone) {
		this.gmtNextVisitPhone = gmtNextVisitPhone;
	}

	public Date getGmtNextVisitEmail() {
		return this.gmtNextVisitEmail;
	}

	public void setGmtNextVisitEmail(Date gmtNextVisitEmail) {
		this.gmtNextVisitEmail = gmtNextVisitEmail;
	}

	public String getVisitTarget() {
		return this.visitTarget;
	}

	public void setVisitTarget(String visitTarget) {
		this.visitTarget = visitTarget;
	}

	public Date getGmtCreated() {
		return this.gmtCreated;
	}

	public void setGmtCreated(Date gmtCreated) {
		this.gmtCreated = gmtCreated;
	}

	public Date getGmtModified() {
		return this.gmtModified;
	}

	public void setGmtModified(Date gmtModified) {
		this.gmtModified = gmtModified;
	}

}