package com.ast.ast1949.domain.auth;

import java.util.Date;

/**
 * AuthUser generated by MyEclipse Persistence Tools
 */

public class AuthUser implements java.io.Serializable {

	// Fields

	/**
	 *
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private String username;
	private String account;
	private String password;
	private String email;
	private String mobile;
	private Integer steping;
	private Date gmtCreated;
	private Date gmtModified;
	private Integer isperson;

	/**
	 * 
	 */
	public AuthUser() {
		super();
	}

	/**
	 * @param username
	 * @param account
	 * @param password
	 * @param email
	 * @param steping
	 * @param gmtCreated
	 * @param gmtLogin
	 */
	public AuthUser(String username, String account, String password,
			String email, Integer steping, Date gmtCreated, Date gmtModified) {
		super();

		this.username = username;
		this.account = account;
		this.password = password;
		this.email = email;
		this.steping = steping;
		this.gmtCreated = gmtCreated;
		this.gmtModified = gmtModified;
	}

	public Integer getIsperson() {
		return isperson;
	}

	public void setIsperson(Integer isperson) {
		this.isperson = isperson;
	}

	public String getMobile() {
		return mobile;
	}

	public void setMobile(String mobile) {
		this.mobile = mobile;
	}

	/**
	 * @return the id
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * @param id
	 *            the id to set
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * @return the username
	 */
	public String getUsername() {
		return username;
	}

	/**
	 * @param username
	 *            the username to set
	 */
	public void setUsername(String username) {
		this.username = username;
	}

	/**
	 * @return the account
	 */
	public String getAccount() {
		return account;
	}

	/**
	 * @param account
	 *            the account to set
	 */
	public void setAccount(String account) {
		this.account = account;
	}

	/**
	 * @return the password
	 */
	public String getPassword() {
		return password;
	}

	/**
	 * @param password
	 *            the password to set
	 */
	public void setPassword(String password) {
		this.password = password;
	}

	/**
	 * @return the email
	 */
	public String getEmail() {
		return email;
	}

	/**
	 * @param email
	 *            the email to set
	 */
	public void setEmail(String email) {
		this.email = email;
	}

	/**
	 * @return the steping
	 */
	public Integer getSteping() {
		return steping;
	}

	/**
	 * @param steping
	 *            the steping to set
	 */
	public void setSteping(Integer steping) {
		this.steping = steping;
	}

	/**
	 * @return the gmtCreated
	 */
	public Date getGmtCreated() {
		return gmtCreated;
	}

	/**
	 * @param gmtCreated
	 *            the gmtCreated to set
	 */
	public void setGmtCreated(Date gmtCreated) {
		this.gmtCreated = gmtCreated;
	}

	/**
	 * @return the gmtModified
	 */
	public Date getGmtModified() {
		return gmtModified;
	}

	/**
	 * @param gmtModified
	 *            the gmtModified to set
	 */
	public void setGmtModified(Date gmtModified) {
		this.gmtModified = gmtModified;
	}

}