package com.ast.ast1949.domain.information;

import java.util.Date;

/**
 * PeriodicalDetails generated by MyEclipse Persistence Tools
 */

public class PeriodicalDetails implements java.io.Serializable {

	// Fields

	/**
	 *
	 */
	private static final long serialVersionUID = 4302920174801457763L;
	private Integer id;
	private Integer periodicalId;
	private String name;
	private String imageName;
	private String previewUrl;
	private Integer orders;
	private Integer pageType;
	private Date gmtModified;
	private Date gmtCreated;

	// Constructors

	/** default constructor */
	public PeriodicalDetails() {
	}

	/** minimal constructor */
	public PeriodicalDetails(Integer id) {
		this.id = id;
	}

	/** full constructor */
	public PeriodicalDetails(Integer id, Integer periodicalId, String name,
			String imageName, String previewUrl, Integer orders,
			Integer pageType, Date gmtModified, Date gmtCreated) {
		this.id = id;
		this.periodicalId = periodicalId;
		this.name = name;
		this.imageName = imageName;
		this.previewUrl = previewUrl;
		this.orders = orders;
		this.pageType = pageType;
		this.gmtModified = gmtModified;
		this.gmtCreated = gmtCreated;
	}

	// Property accessors

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getPeriodicalId() {
		return this.periodicalId;
	}

	public void setPeriodicalId(Integer periodicalId) {
		this.periodicalId = periodicalId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getImageName() {
		return this.imageName;
	}

	public void setImageName(String imageName) {
		this.imageName = imageName;
	}

	public String getPreviewUrl() {
		return this.previewUrl;
	}

	public void setPreviewUrl(String previewUrl) {
		this.previewUrl = previewUrl;
	}

	public Integer getOrders() {
		return this.orders;
	}

	public void setOrders(Integer orders) {
		this.orders = orders;
	}

	public Integer getPageType() {
		return this.pageType;
	}

	public void setPageType(Integer pageType) {
		this.pageType = pageType;
	}

	public Date getGmtModified() {
		return this.gmtModified;
	}

	public void setGmtModified(Date gmtModified) {
		this.gmtModified = gmtModified;
	}

	public Date getGmtCreated() {
		return this.gmtCreated;
	}

	public void setGmtCreated(Date gmtCreated) {
		this.gmtCreated = gmtCreated;
	}

}