package com.ast.ast1949.domain.information;

import java.util.Date;

/**
 * Periodical generated by MyEclipse Persistence Tools
 */

public class Periodical implements java.io.Serializable {

	// Fields

	/**
	 *
	 */
	private static final long serialVersionUID = -463485434648116211L;
	private Integer id;
	private String name;
	private String cycle;
	private Integer numView;
	private Integer numUp;
	private String pdfDownload;
	private Float size;
	private Date gmtRelease;
	private Integer numRelease;
	private String releaseNo;
	private Date gmtModified;
	private Date gmtCreated;
	private String zipPath;

	// Constructors

	/** default constructor */
	public Periodical() {
	}

	/** minimal constructor */
	public Periodical(Integer id) {
		this.id = id;
	}

	/** full constructor */
	public Periodical(Integer id, String name, String cycle, Integer numView,
			Integer numUp, String pdfDownload, Float size, Date gmtRelease,
			Integer numRelease, String releaseNo, Date gmtModified,
			Date gmtCreated) {
		this.id = id;
		this.name = name;
		this.cycle = cycle;
		this.numView = numView;
		this.numUp = numUp;
		this.pdfDownload = pdfDownload;
		this.size = size;
		this.gmtRelease = gmtRelease;
		this.numRelease = numRelease;
		this.releaseNo = releaseNo;
		this.gmtModified = gmtModified;
		this.gmtCreated = gmtCreated;
	}

	// Property accessors

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getCycle() {
		return this.cycle;
	}

	public void setCycle(String cycle) {
		this.cycle = cycle;
	}

	public Integer getNumView() {
		return this.numView;
	}

	public void setNumView(Integer numView) {
		this.numView = numView;
	}

	public Integer getNumUp() {
		return this.numUp;
	}

	public void setNumUp(Integer numUp) {
		this.numUp = numUp;
	}

	public String getPdfDownload() {
		return this.pdfDownload;
	}

	public void setPdfDownload(String pdfDownload) {
		this.pdfDownload = pdfDownload;
	}

	public Float getSize() {
		return this.size;
	}

	public void setSize(Float size) {
		this.size = size;
	}

	public Date getGmtRelease() {
		return this.gmtRelease;
	}

	public void setGmtRelease(Date gmtRelease) {
		this.gmtRelease = gmtRelease;
	}

	public Integer getNumRelease() {
		return this.numRelease;
	}

	public void setNumRelease(Integer numRelease) {
		this.numRelease = numRelease;
	}

	public String getReleaseNo() {
		return this.releaseNo;
	}

	public void setReleaseNo(String releaseNo) {
		this.releaseNo = releaseNo;
	}

	public Date getGmtModified() {
		return this.gmtModified;
	}

	public void setGmtModified(Date gmtModified) {
		this.gmtModified = gmtModified;
	}

	public Date getGmtCreated() {
		return this.gmtCreated;
	}

	public void setGmtCreated(Date gmtCreated) {
		this.gmtCreated = gmtCreated;
	}

	/**
	 * @return the zipPath
	 */
	public String getZipPath() {
		return zipPath;
	}

	/**
	 * @param zipPath the zipPath to set
	 */
	public void setZipPath(String zipPath) {
		this.zipPath = zipPath;
	}



}