package com.ast.ast1949.domain.company;

import java.util.Date;

/**
 * CompanyUploadFile generated by MyEclipse Persistence Tools
 */

public class CompanyUploadFileDO implements java.io.Serializable {

	// Fields

	/**
	 *
	 */
	private static final long serialVersionUID = 2700450381204039580L;

	private Integer id;
	private Integer companyId;
	private String filename;
	private String filetype;
	private String filepath;
	private String remark;
	private Date gmtCreated;
	private Date gmtModified;

	// Constructors

	/** default constructor */
	public CompanyUploadFileDO() {
	}

	/** minimal constructor */
	public CompanyUploadFileDO(Integer id) {
		this.id = id;
	}

	/** full constructor */
	public CompanyUploadFileDO(Integer id, Integer companyId, String filename,
			String filetype, String filepath, String remark, Date gmtCreated,
			Date gmtModified) {
		this.id = id;
		this.companyId = companyId;
		this.filename = filename;
		this.filetype = filetype;
		this.filepath = filepath;
		this.remark = remark;
		this.gmtCreated = gmtCreated;
		this.gmtModified = gmtModified;
	}

	// Property accessors

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getCompanyId() {
		return this.companyId;
	}

	public void setCompanyId(Integer companyId) {
		this.companyId = companyId;
	}

	public String getFilename() {
		return this.filename;
	}

	public void setFilename(String filename) {
		this.filename = filename;
	}

	public String getFiletype() {
		return this.filetype;
	}

	public void setFiletype(String filetype) {
		this.filetype = filetype;
	}

	public String getFilepath() {
		return this.filepath;
	}

	public void setFilepath(String filepath) {
		this.filepath = filepath;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public Date getGmtCreated() {
		return this.gmtCreated;
	}

	public void setGmtCreated(Date gmtCreated) {
		this.gmtCreated = gmtCreated;
	}

	public Date getGmtModified() {
		return this.gmtModified;
	}

	public void setGmtModified(Date gmtModified) {
		this.gmtModified = gmtModified;
	}

}