package com.ast.ast1949.domain.company;

import java.util.Date;

/**
 * CompanyCustomersGroup generated by MyEclipse Persistence Tools
 */

public class CompanyCustomersGroupDO implements java.io.Serializable {

	// Fields

	/**
	 *
	 */
	private static final long serialVersionUID = 3613025721788319317L;
	private Integer id;
	private String name;
	private String remark;
	private Integer companyId;
	private String account;
	private Date gmtCreated;
	private Date gmtModified;

	// Constructors

	/** default constructor */
	public CompanyCustomersGroupDO() {
	}

	/** minimal constructor */
	public CompanyCustomersGroupDO(Integer id) {
		this.id = id;
	}

	/** full constructor */
	public CompanyCustomersGroupDO(Integer id, String name, String remark,
			Integer companyId, String account, Date gmtCreated, Date gmtModified) {
		this.id = id;
		this.name = name;
		this.remark = remark;
		this.companyId = companyId;
		this.account = account;
		this.gmtCreated = gmtCreated;
		this.gmtModified = gmtModified;
	}

	// Property accessors

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public Integer getCompanyId() {
		return this.companyId;
	}

	public void setCompanyId(Integer companyId) {
		this.companyId = companyId;
	}

	public String getAccount() {
		return this.account;
	}

	public void setAccount(String account) {
		this.account = account;
	}

	public Date getGmtCreated() {
		return this.gmtCreated;
	}

	public void setGmtCreated(Date gmtCreated) {
		this.gmtCreated = gmtCreated;
	}

	public Date getGmtModified() {
		return this.gmtModified;
	}

	public void setGmtModified(Date gmtModified) {
		this.gmtModified = gmtModified;
	}

}