package com.ast.ast1949.domain.company;

import java.util.Date;

import com.ast.ast1949.domain.DomainSupport;

/**
 * 询盘留言 Inquiry generated by MyEclipse Persistence Tools
 */

public class Inquiry extends DomainSupport {

	// Fields

	/**
	 *
	 */
	private static final long serialVersionUID = 1L;
	//	private Integer id;
	private String title;//    title '询盘标题',
	private String content;//    content '询盘内容',
	private String conversationGroup; //会话组
	private Integer groupId;//    group_id 询盘分组id
	private String beInquiredType;//    be_inquired_type '询盘目标对象的类型 0:供求信息 1:公司 2: 询盘',
	private Integer beInquiredId;//    be_inquired_id '询盘对象的ID号',
	private String inquiredType;//    inquired_type 询盘产生的方式 0－前台客户直接留言，1－后台询盘导入产生，2－后台供求信息导入产生
	private Integer inquiredId;//  inquired_id  TYPE为1，2时为相应的信息ID
	private String senderAccount;
	private String receiverAccount;
	private String batchSendType;//    batch_send_type 群发标志',
	private String exportStatus;//    export_status '导出处理状态标志',
	private String exportPerson;//    export_person '处理人,处理导出的登录账号',
	private String isRubbish;//    is_rubbish '是否为垃圾留言(0:否,1:是)',
	private String isViewed;//    is_viewed '是否查看标志',
	private String isSenderDel;//    is_sender_del '删除标志',
	private Date sendTime;//    send_time '发送时间',
	private String isReplyed;
	private String isReceiverDel;//    is_receiver_del '删除标志'
	private Date gmtCreated;//    gmt_created '添加时间'
	private Date gmtModified;//    gmt_modified '修改时间'
	
	/**
	 * @return the title
	 */
	public String getTitle() {
		return title;
	}
	/**
	 * @param title the title to set
	 */
	public void setTitle(String title) {
		this.title = title;
	}
	/**
	 * @return the content
	 */
	public String getContent() {
		return content;
	}
	/**
	 * @param content the content to set
	 */
	public void setContent(String content) {
		this.content = content;
	}
	/**
	 * @return the groupId
	 */
	public Integer getGroupId() {
		return groupId;
	}
	/**
	 * @param groupId the groupId to set
	 */
	public void setGroupId(Integer groupId) {
		this.groupId = groupId;
	}
	/**
	 * @return the beInquiredType
	 */
	public String getBeInquiredType() {
		return beInquiredType;
	}
	/**
	 * @param beInquiredType the beInquiredType to set
	 */
	public void setBeInquiredType(String beInquiredType) {
		this.beInquiredType = beInquiredType;
	}
	/**
	 * @return the beInquiredId
	 */
	public Integer getBeInquiredId() {
		return beInquiredId;
	}
	/**
	 * @param beInquiredId the beInquiredId to set
	 */
	public void setBeInquiredId(Integer beInquiredId) {
		this.beInquiredId = beInquiredId;
	}
	/**
	 * @return the inquiredType
	 */
	public String getInquiredType() {
		return inquiredType;
	}
	/**
	 * @param inquiredType the inquiredType to set
	 */
	public void setInquiredType(String inquiredType) {
		this.inquiredType = inquiredType;
	}
	/**
	 * @return the inquiredId
	 */
	public Integer getInquiredId() {
		return inquiredId;
	}
	/**
	 * @param inquiredId the inquiredId to set
	 */
	public void setInquiredId(Integer inquiredId) {
		this.inquiredId = inquiredId;
	}
	/**
	 * @return the senderAccount
	 */
	public String getSenderAccount() {
		return senderAccount;
	}
	/**
	 * @param senderAccount the senderAccount to set
	 */
	public void setSenderAccount(String senderAccount) {
		this.senderAccount = senderAccount;
	}
	/**
	 * @return the receiverAccount
	 */
	public String getReceiverAccount() {
		return receiverAccount;
	}
	/**
	 * @param receiverAccount the receiverAccount to set
	 */
	public void setReceiverAccount(String receiverAccount) {
		this.receiverAccount = receiverAccount;
	}
	/**
	 * @return the batchSendType
	 */
	public String getBatchSendType() {
		return batchSendType;
	}
	/**
	 * @param batchSendType the batchSendType to set
	 */
	public void setBatchSendType(String batchSendType) {
		this.batchSendType = batchSendType;
	}
	/**
	 * @return the exportStatus
	 */
	public String getExportStatus() {
		return exportStatus;
	}
	/**
	 * @param exportStatus the exportStatus to set
	 */
	public void setExportStatus(String exportStatus) {
		this.exportStatus = exportStatus;
	}
	/**
	 * @return the exportPerson
	 */
	public String getExportPerson() {
		return exportPerson;
	}
	/**
	 * @param exportPerson the exportPerson to set
	 */
	public void setExportPerson(String exportPerson) {
		this.exportPerson = exportPerson;
	}
	/**
	 * @return the isRubbish
	 */
	public String getIsRubbish() {
		return isRubbish;
	}
	/**
	 * @param isRubbish the isRubbish to set
	 */
	public void setIsRubbish(String isRubbish) {
		this.isRubbish = isRubbish;
	}
	/**
	 * @return the isViewed
	 */
	public String getIsViewed() {
		return isViewed;
	}
	/**
	 * @param isViewed the isViewed to set
	 */
	public void setIsViewed(String isViewed) {
		this.isViewed = isViewed;
	}
	/**
	 * @return the isSenderDel
	 */
	public String getIsSenderDel() {
		return isSenderDel;
	}
	/**
	 * @param isSenderDel the isSenderDel to set
	 */
	public void setIsSenderDel(String isSenderDel) {
		this.isSenderDel = isSenderDel;
	}
	/**
	 * @return the sendTime
	 */
	public Date getSendTime() {
		return sendTime;
	}
	/**
	 * @param sendTime the sendTime to set
	 */
	public void setSendTime(Date sendTime) {
		this.sendTime = sendTime;
	}
	/**
	 * @return the isReplyed
	 */
	public String getIsReplyed() {
		return isReplyed;
	}
	/**
	 * @param isReplyed the isReplyed to set
	 */
	public void setIsReplyed(String isReplyed) {
		this.isReplyed = isReplyed;
	}
	/**
	 * @return the isReceiverDel
	 */
	public String getIsReceiverDel() {
		return isReceiverDel;
	}
	/**
	 * @param isReceiverDel the isReceiverDel to set
	 */
	public void setIsReceiverDel(String isReceiverDel) {
		this.isReceiverDel = isReceiverDel;
	}
	/**
	 * @return the gmtCreated
	 */
	public Date getGmtCreated() {
		return gmtCreated;
	}
	/**
	 * @param gmtCreated the gmtCreated to set
	 */
	public void setGmtCreated(Date gmtCreated) {
		this.gmtCreated = gmtCreated;
	}
	/**
	 * @return the gmtModified
	 */
	public Date getGmtModified() {
		return gmtModified;
	}
	/**
	 * @param gmtModified the gmtModified to set
	 */
	public void setGmtModified(Date gmtModified) {
		this.gmtModified = gmtModified;
	}
	/**
	 * @return the conversationGroup
	 */
	public String getConversationGroup() {
		return conversationGroup;
	}
	/**
	 * @param conversationGroup the conversationGroup to set
	 */
	public void setConversationGroup(String conversationGroup) {
		this.conversationGroup = conversationGroup;
	}
	
}