package com.zz91.ep.domain.common;

import java.util.Date;

/**
 * SysProject generated by MyEclipse Persistence Tools
 */

public class SysProject implements java.io.Serializable {

	// Fields

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private String name;
	private String code;
	private String password;
	private String rightCode;
	private String url;
	private String avatar;
	private String remark;
	private Date gmtCreated;
	private String version;
	private Date gmtModified;

	// Constructors

	/** default constructor */
	public SysProject() {
	}

	/** minimal constructor */
	public SysProject(Integer id, String name, String code, String password,
			Date gmtCreated, Date gmtModified) {
		this.id = id;
		this.name = name;
		this.code = code;
		this.password = password;
		this.gmtCreated = gmtCreated;
		this.gmtModified = gmtModified;
	}

	/** full constructor */
	public SysProject(Integer id, String name, String code, String password,
			String rightCode, String url, String avatar, String remark,
			Date gmtCreated, String version, Date gmtModified) {
		this.id = id;
		this.name = name;
		this.code = code;
		this.password = password;
		this.rightCode = rightCode;
		this.url = url;
		this.avatar = avatar;
		this.remark = remark;
		this.gmtCreated = gmtCreated;
		this.version = version;
		this.gmtModified = gmtModified;
	}

	// Property accessors

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getRightCode() {
		return this.rightCode;
	}

	public void setRightCode(String rightCode) {
		this.rightCode = rightCode;
	}

	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	public String getAvatar() {
		return this.avatar;
	}

	public void setAvatar(String avatar) {
		this.avatar = avatar;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public Date getGmtCreated() {
		return this.gmtCreated;
	}

	public void setGmtCreated(Date gmtCreated) {
		this.gmtCreated = gmtCreated;
	}

	public String getVersion() {
		return this.version;
	}

	public void setVersion(String version) {
		this.version = version;
	}

	public Date getGmtModified() {
		return this.gmtModified;
	}

	public void setGmtModified(Date gmtModified) {
		this.gmtModified = gmtModified;
	}

}