package com.ast.ast1949.domain.products;

import java.util.Date;

/**
 * CategoryProducts generated by MyEclipse Persistence Tools
 */

public class CategoryProductsDO implements java.io.Serializable {

	// Fields

	/**
	 *
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private String code;
	private String label;
	private String isAssist;  //辅助类别
	private String isDel;     //是否删除
	private Date gmtCreated;
	private Date gmtModified;
	private String cnspell;

	// Constructors

	/** default constructor */
	public CategoryProductsDO() {
	}

	/** minimal constructor */
	public CategoryProductsDO(Integer id) {
		this.id = id;
	}

	/** full constructor */
	public CategoryProductsDO(Integer id, String code, String label,
			String isAssist, String isDel, Date gmtCreated, Date gmtModified) {
		this.id = id;
		this.code = code;
		this.label = label;
		this.isAssist = isAssist;
		this.isDel = isDel;
		this.gmtCreated = gmtCreated;
		this.gmtModified = gmtModified;
	}

	// Property accessors

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public String getLabel() {
		return this.label;
	}

	public void setLabel(String label) {
		this.label = label;
	}

	public String getIsAssist() {
		return this.isAssist;
	}

	public void setIsAssist(String isAssist) {
		this.isAssist = isAssist;
	}

	public String getIsDel() {
		return this.isDel;
	}

	public void setIsDel(String isDel) {
		this.isDel = isDel;
	}

	public Date getGmtCreated() {
		return this.gmtCreated;
	}

	public void setGmtCreated(Date gmtCreated) {
		this.gmtCreated = gmtCreated;
	}

	public Date getGmtModified() {
		return this.gmtModified;
	}

	public void setGmtModified(Date gmtModified) {
		this.gmtModified = gmtModified;
	}

	/**
	 * @return the cnspell
	 */
	public String getCnspell() {
		return cnspell;
	}

	/**
	 * @param cnspell the cnspell to set
	 */
	public void setCnspell(String cnspell) {
		this.cnspell = cnspell;
	}



}