package com.ast.ast1949.domain.products;

import java.util.Date;

import com.ast.ast1949.domain.DomainSupport;

/**
 * Products generated by MyEclipse Persistence Tools
 */

public class ProductsDO extends DomainSupport {
	/**
	 *
	 */
	private static final long serialVersionUID = 1L;
	private Integer companyId; // 发布公司ID
	private String account;
	private String productsTypeCode;
	private String sourceTypeCode;
	private String title;
	private String details;
	private String location;
	private String provideStatus;
	private String totalQuantity;
	private String isShowInPrice;
	private String priceUnit;
	private String price;
	private String quantityUnit;
	private String quantity;
	private String source;
	private String specification;
	private String origin;
	private String impurity;
	private String color;
	private String useful;
	private String appearance;
	private String manufacture;
	private String remark;
	private String postType;
	private String isPause; //0:发布 1:暂停发布 
	private Boolean isPostWhenViewLimit;
	private Boolean isPostFromInquiry;
	private Boolean isDel; // 是否删除
	private Boolean isVip; // 是否高会
	private String categoryProductsMainCode; // 供求主类别code
	private String categoryProductsAssistCode; // 供求辅助类别
	private String checkPerson;
	private String checkStatus;
	private String uncheckedCheckStatus;
	private String unpassReason;
	private Date checkTime;
	private Date realTime;
	private Date refreshTime;
	private Date expireTime;
	private Date gmtCreated;
	private Date gmtModified;
	private Float minPrice; // 价格下限
	private Float maxPrice; // 价格上限
	private String goodsTypeCode; // 货物类型：期货或现货，对应code(1036)
	private String tags;
	private String tagsAdmin;
	private Integer shipDay; //多少天可以发货
	private String strShipDay;//将发货时间映射成string类型
	private String crmCompanySvr; // 服务code
	private String expireFlag; // 用于后台搜索 exprieFlag 供求过期标志  1:已过期， 0：未过期
	private String chRefreshFlag;//生意管家 供求管理页面中 刷新是否为立即刷新 针对已审核列表中长期有效但长时间未更新的供求 设置chRefreshFlag=1
	private String exRefreshFlag;//生意管家 供求管理页面中 刷新是否为立即刷新 针对已过期列表中已审核但已过期的供求 设置exRefreshFlag=1
	private String hide;//1:表示这条信息已隐藏
	
	private Integer score; // 供求星级分数
	

	public String getHide() {
		return hide;
	}

	public void setHide(String hide) {
		this.hide = hide;
	}

	public String getChRefreshFlag() {
		return chRefreshFlag;
	}

	public void setChRefreshFlag(String chRefreshFlag) {
		this.chRefreshFlag = chRefreshFlag;
	}

	public String getExRefreshFlag() {
		return exRefreshFlag;
	}

	public void setExRefreshFlag(String exRefreshFlag) {
		this.exRefreshFlag = exRefreshFlag;
	}

	public String getIsPause() {
		return isPause;
	}

	public void setIsPause(String isPause) {
		this.isPause = isPause;
	}

	public String getExpireFlag() {
		return expireFlag;
	}

	public void setExpireFlag(String expireFlag) {
		this.expireFlag = expireFlag;
	}

	// 图片审核不过标记
	private Integer isPicPass;
	// 是否导出询盘
	private Boolean isExportInquiry;
	private Boolean isNotExportInquiry;
	// 是否样品
	private Boolean isYP;
	private Boolean isBaoyou;
	private String sampleReason;
	
	private Integer searchRangeRefresh; // 刷新时间 范围 天数
	private String membershipCode; //会员级别

	/** default constructor */
	public ProductsDO() {
	}

	public Integer getCompanyId() {
		return this.companyId;
	}

	public void setCompanyId(Integer companyId) {
		this.companyId = companyId;
	}

	public String getProductsTypeCode() {
		return this.productsTypeCode;
	}

	public void setProductsTypeCode(String productsTypeCode) {
		this.productsTypeCode = productsTypeCode;
	}

	public String getSourceTypeCode() {
		return this.sourceTypeCode;
	}

	public void setSourceTypeCode(String sourceTypeCode) {
		this.sourceTypeCode = sourceTypeCode;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getDetails() {
		return this.details;
	}

	public void setDetails(String details) {
		this.details = details;
	}

	public String getLocation() {
		return this.location;
	}

	public void setLocation(String location) {
		this.location = location;
	}

	public String getProvideStatus() {
		return this.provideStatus;
	}

	public void setProvideStatus(String provideStatus) {
		this.provideStatus = provideStatus;
	}

	public String getTotalQuantity() {
		return this.totalQuantity;
	}

	public void setTotalQuantity(String totalQuantity) {
		this.totalQuantity = totalQuantity;
	}

	public String getIsShowInPrice() {
		return this.isShowInPrice;
	}

	public void setIsShowInPrice(String isShowInPrice) {
		this.isShowInPrice = isShowInPrice;
	}

	public String getPriceUnit() {
		return this.priceUnit;
	}

	public void setPriceUnit(String priceUnit) {
		this.priceUnit = priceUnit;
	}

	public String getPrice() {
		return this.price;
	}

	public void setPrice(String price) {
		this.price = price;
	}

	public String getQuantityUnit() {
		return this.quantityUnit;
	}

	public void setQuantityUnit(String quantityUnit) {
		this.quantityUnit = quantityUnit;
	}

	public String getQuantity() {
		return this.quantity;
	}

	public void setQuantity(String quantity) {
		this.quantity = quantity;
	}

	public String getSource() {
		return this.source;
	}

	public void setSource(String source) {
		this.source = source;
	}

	public String getSpecification() {
		return this.specification;
	}

	public void setSpecification(String specification) {
		this.specification = specification;
	}

	public String getOrigin() {
		return this.origin;
	}

	public void setOrigin(String origin) {
		this.origin = origin;
	}

	public String getImpurity() {
		return this.impurity;
	}

	public void setImpurity(String impurity) {
		this.impurity = impurity;
	}

	public String getColor() {
		return this.color;
	}

	public void setColor(String color) {
		this.color = color;
	}

	public String getUseful() {
		return this.useful;
	}

	public void setUseful(String useful) {
		this.useful = useful;
	}

	public String getAppearance() {
		return this.appearance;
	}

	public void setAppearance(String appearance) {
		this.appearance = appearance;
	}

	public String getManufacture() {
		return this.manufacture;
	}

	public void setManufacture(String manufacture) {
		this.manufacture = manufacture;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public String getPostType() {
		return this.postType;
	}

	public void setPostType(String postType) {
		this.postType = postType;
	}

	public Boolean getIsPostWhenViewLimit() {
		return this.isPostWhenViewLimit;
	}

	public void setIsPostWhenViewLimit(Boolean isPostWhenViewLimit) {
		this.isPostWhenViewLimit = isPostWhenViewLimit;
	}

	public Boolean getIsDel() {
		return this.isDel;
	}

	public void setIsDel(Boolean isDel) {
		this.isDel = isDel;
	}

	public String getCategoryProductsMainCode() {
		return categoryProductsMainCode;
	}

	public void setCategoryProductsMainCode(String categoryProductsMainCode) {
		this.categoryProductsMainCode = categoryProductsMainCode;
	}

	public String getCategoryProductsAssistCode() {
		return categoryProductsAssistCode;
	}

	public void setCategoryProductsAssistCode(String categoryProductsAssistCode) {
		this.categoryProductsAssistCode = categoryProductsAssistCode;
	}

	public String getCheckPerson() {
		return this.checkPerson;
	}

	public void setCheckPerson(String checkPerson) {
		this.checkPerson = checkPerson;
	}

	public String getCheckStatus() {
		return this.checkStatus;
	}

	public void setCheckStatus(String checkStatus) {
		this.checkStatus = checkStatus;
	}

	public String getUncheckedCheckStatus() {
		return uncheckedCheckStatus;
	}

	public void setUncheckedCheckStatus(String uncheckedCheckStatus) {
		this.uncheckedCheckStatus = uncheckedCheckStatus;
	}

	public String getUnpassReason() {
		return unpassReason;
	}

	public void setUnpassReason(String unpassReason) {
		this.unpassReason = unpassReason;
	}

	public Date getCheckTime() {
		return this.checkTime;
	}

	public void setCheckTime(Date checkTime) {
		this.checkTime = checkTime;
	}

	public Date getRealTime() {
		return this.realTime;
	}

	public void setRealTime(Date realTime) {
		this.realTime = realTime;
	}

	public Date getRefreshTime() {
		return this.refreshTime;
	}

	public void setRefreshTime(Date refreshTime) {
		this.refreshTime = refreshTime;
	}

	public Date getExpireTime() {
		return this.expireTime;
	}

	public void setExpireTime(Date expireTime) {
		this.expireTime = expireTime;
	}

	public Date getGmtCreated() {
		return this.gmtCreated;
	}

	public void setGmtCreated(Date gmtCreated) {
		this.gmtCreated = gmtCreated;
	}

	public Date getGmtModified() {
		return this.gmtModified;
	}

	public void setGmtModified(Date gmtModified) {
		this.gmtModified = gmtModified;
	}

	public void setAccount(String account) {
		this.account = account;
	}

	public String getAccount() {
		return account;
	}

	public void setIsPostFromInquiry(Boolean isPostFromInquiry) {
		this.isPostFromInquiry = isPostFromInquiry;
	}

	public Boolean getIsPostFromInquiry() {
		return isPostFromInquiry;
	}

	public Float getMinPrice() {
		return minPrice;
	}

	public void setMinPrice(Float minPrice) {
		this.minPrice = minPrice;
	}

	public Float getMaxPrice() {
		return maxPrice;
	}

	public void setMaxPrice(Float maxPrice) {
		this.maxPrice = maxPrice;
	}

	public String getGoodsTypeCode() {
		return goodsTypeCode;
	}

	public void setGoodsTypeCode(String goodsTypeCode) {
		this.goodsTypeCode = goodsTypeCode;
	}

	/**
	 * @return the tags
	 */
	public String getTags() {
		return tags;
	}

	/**
	 * @param tags
	 *            the tags to set
	 */
	public void setTags(String tags) {
		this.tags = tags;
	}

	/**
	 * @return the tagsAdmin
	 */
	public String getTagsAdmin() {
		return tagsAdmin;
	}

	/**
	 * @param tagsAdmin
	 *            the tagsAdmin to set
	 */
	public void setTagsAdmin(String tagsAdmin) {
		this.tagsAdmin = tagsAdmin;
	}

	public Boolean getIsVip() {
		return isVip;
	}

	public void setIsVip(Boolean isVip) {
		this.isVip = isVip;
	}

	public Integer getShipDay() {
		return shipDay;
	}

	public void setShipDay(Integer shipDay) {
	    if (shipDay == null) {
	        strShipDay = "";
	    } else {
	        strShipDay = String.valueOf(shipDay);
	    }
	    this.shipDay = shipDay;
	}

	public String getStrShipDay() {
        return strShipDay;
    }

    public void setStrShipDay(String strShipDay) {
        this.strShipDay = strShipDay;
    }

    public String getCrmCompanySvr() {
		return crmCompanySvr;
	}

	public void setCrmCompanySvr(String crmCompanySvr) {
		this.crmCompanySvr = crmCompanySvr;
	}

	public Integer getIsPicPass() {
		return isPicPass;
	}

	public void setIsPicPass(Integer isPicPass) {
		this.isPicPass = isPicPass;
	}

	public Boolean getIsExportInquiry() {
		return isExportInquiry;
	}

	public void setIsExportInquiry(Boolean isExportInquiry) {
		this.isExportInquiry = isExportInquiry;
	}

	public Boolean getIsNotExportInquiry() {
		return isNotExportInquiry;
	}

	public void setIsNotExportInquiry(Boolean isNotExportInquiry) {
		this.isNotExportInquiry = isNotExportInquiry;
	}

	public Boolean getIsYP() {
		return isYP;
	}

	public void setIsYP(Boolean isYP) {
		this.isYP = isYP;
	}

	public Boolean getIsBaoyou() {
		return isBaoyou;
	}

	public void setIsBaoyou(Boolean isBaoyou) {
		this.isBaoyou = isBaoyou;
	}

	public Integer getSearchRangeRefresh() {
		return searchRangeRefresh;
	}

	public void setSearchRangeRefresh(Integer searchRangeRefresh) {
		this.searchRangeRefresh = searchRangeRefresh;
	}

	public String getSampleReason() {
		return sampleReason;
	}

	public void setSampleReason(String sampleReason) {
		this.sampleReason = sampleReason;
	}

	public String getMembershipCode() {
		return membershipCode;
	}

	public void setMembershipCode(String membershipCode) {
		this.membershipCode = membershipCode;
	}

	public Integer getScore() {
		return score;
	}

	public void setScore(Integer score) {
		this.score = score;
	}
	
}