package com.ast.ast1949.domain.products;

import java.util.Date;

/**
 * ProductsAlbums generated by MyEclipse Persistence Tools
 */

public class ProductsAlbumsDO implements java.io.Serializable {

	// Fields

	/**
	 *
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private Integer parentId;
	private String name;
	private String isDelete;
	private Date gmtCreated;
	private Date gmtModified;

	// Constructors

	/** default constructor */
	public ProductsAlbumsDO() {
	}

	/** minimal constructor */
	public ProductsAlbumsDO(Integer id) {
		this.id = id;
	}

	/** full constructor */
	public ProductsAlbumsDO(Integer id, Integer parentId, String name,
			Date gmtCreated, Date gmtModified) {
		this.id = id;
		this.parentId = parentId;
		this.name = name;
		this.gmtCreated = gmtCreated;
		this.gmtModified = gmtModified;
	}

	// Property accessors

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getParentId() {
		return this.parentId;
	}

	public void setParentId(Integer parentId) {
		this.parentId = parentId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getIsDelete() {
		return isDelete;
	}

	public void setIsDelete(String isDelete) {
		this.isDelete = isDelete;
	}


	public Date getGmtCreated() {
		return this.gmtCreated;
	}

	public void setGmtCreated(Date gmtCreated) {
		this.gmtCreated = gmtCreated;
	}

	public Date getGmtModified() {
		return this.gmtModified;
	}

	public void setGmtModified(Date gmtModified) {
		this.gmtModified = gmtModified;
	}

}