package com.ast.ast1949.domain.products;

import java.util.Date;

/**
 * ProductsPic generated by MyEclipse Persistence Tools
 */

public class ProductsPicDO implements java.io.Serializable {

	// Fields

	/**
	 *
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private Integer productId;
	private String picAddress;
	private Integer albumId;
	private String isDefault; //是否为客户默认显示的图片
	private String isCover;   //是否为相册的封面图片
	private Date gmtCreated;
	private Date gmtModified;
	private String name;
	private String checkStatus; //针对所有用户的审核状态 0:未审核,1:审核通过,2:审核不通过
	private String unpassReason; // 不通过原因

	// Constructors

	/** default constructor */
	public ProductsPicDO() {
	}

	/** minimal constructor */
	public ProductsPicDO(Integer id) {
		this.id = id;
	}

	/** full constructor */
	public ProductsPicDO(Integer id, Integer productId, String picAddress,
			Integer albumId, Date gmtCreated, Date gmtModified) {
		this.id = id;
		this.productId = productId;
		this.picAddress = picAddress;
		this.albumId = albumId;
		this.gmtCreated = gmtCreated;
		this.gmtModified = gmtModified;
	}

	// Property accessors

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getProductId() {
		return this.productId;
	}

	public void setProductId(Integer productId) {
		this.productId = productId;
	}

	public String getPicAddress() {
		return this.picAddress;
	}

	public void setPicAddress(String picAddress) {
		this.picAddress = picAddress;
	}

	public Integer getAlbumId() {
		return this.albumId;
	}

	public void setAlbumId(Integer albumId) {
		this.albumId = albumId;
	}

	public String getIsDefault() {
		return isDefault;
	}

	public void setIsDefault(String isDefault) {
		this.isDefault = isDefault;
	}

	public String getIsCover() {
		return isCover;
	}

	public void setIsCover(String isCover) {
		this.isCover = isCover;
	}

	public Date getGmtCreated() {
		return this.gmtCreated;
	}

	public void setGmtCreated(Date gmtCreated) {
		this.gmtCreated = gmtCreated;
	}

	public Date getGmtModified() {
		return this.gmtModified;
	}

	public void setGmtModified(Date gmtModified) {
		this.gmtModified = gmtModified;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getCheckStatus() {
		return checkStatus;
	}

	public String getUnpassReason() {
		return unpassReason;
	}

	public void setCheckStatus(String checkStatus) {
		this.checkStatus = checkStatus;
	}

	public void setUnpassReason(String unpassReason) {
		this.unpassReason = unpassReason;
	}

}