package com.ast.ast1949.domain.products;

import java.util.Date;

/**
 * ProductsRelateCategory generated by MyEclipse Persistence Tools
 */

public class ProductsRelateCategoryDO implements java.io.Serializable {

	// Fields

	/**
	 *
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private Integer productId;
	private Integer productCategoryId;
	private Date gmtCreated;
	private Date gmtModified;

	// Constructors

	/** default constructor */
	public ProductsRelateCategoryDO() {
	}

	/** minimal constructor */
	public ProductsRelateCategoryDO(Integer id) {
		this.id = id;
	}

	/** full constructor */
	public ProductsRelateCategoryDO(Integer id, Integer productId,
			Integer productCategoryId, Date gmtCreated, Date gmtModified) {
		this.id = id;
		this.productId = productId;
		this.productCategoryId = productCategoryId;
		this.gmtCreated = gmtCreated;
		this.gmtModified = gmtModified;
	}

	// Property accessors

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getProductId() {
		return this.productId;
	}

	public void setProductId(Integer productId) {
		this.productId = productId;
	}

	public Integer getProductCategoryId() {
		return this.productCategoryId;
	}

	public void setProductCategoryId(Integer productCategoryId) {
		this.productCategoryId = productCategoryId;
	}

	public Date getGmtCreated() {
		return this.gmtCreated;
	}

	public void setGmtCreated(Date gmtCreated) {
		this.gmtCreated = gmtCreated;
	}

	public Date getGmtModified() {
		return this.gmtModified;
	}

	public void setGmtModified(Date gmtModified) {
		this.gmtModified = gmtModified;
	}

}