//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行库版本:2.0.50727.42
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rcu_En_News.Web.News {
    
    
    /// <summary>
    /// Add 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Add 
    {
        
		protected global::System.Web.UI.WebControls.TextBox txtNews_Title;
		protected global::System.Web.UI.WebControls.TextBox txtNews_Contents;
		protected global::System.Web.UI.WebControls.TextBox txtClass_Code;
		protected global::System.Web.UI.WebControls.TextBox txtCountry_Id;
		protected global::System.Web.UI.WebControls.TextBox txtNews_Date;
		protected global::System.Web.UI.WebControls.CheckBox chkNews_state;
		protected global::System.Web.UI.WebControls.TextBox txtBig_Pic;
		protected global::System.Web.UI.WebControls.TextBox txtSmall_Pic;
		protected global::System.Web.UI.WebControls.TextBox txtNews_Poster;
		protected global::System.Web.UI.WebControls.TextBox txtNews_Hits;
		protected global::System.Web.UI.WebControls.TextBox txtMsg_Counts;
		protected global::System.Web.UI.WebControls.TextBox txtLables;
	protected global::System.Web.UI.WebControls.Button btnAdd;
	protected global::System.Web.UI.WebControls.Button btnCancel;

    }
}
