//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行库版本:2.0.50727.42
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rcu_En_News.Web.News {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblNews_Id;
	protected global::System.Web.UI.WebControls.Label lblNews_Title;
	protected global::System.Web.UI.WebControls.Label lblNews_Contents;
	protected global::System.Web.UI.WebControls.Label lblClass_Code;
	protected global::System.Web.UI.WebControls.Label lblCountry_Id;
	protected global::System.Web.UI.WebControls.Label lblNews_Date;
	protected global::System.Web.UI.WebControls.CheckBox chkNews_state;
	protected global::System.Web.UI.WebControls.Label lblBig_Pic;
	protected global::System.Web.UI.WebControls.Label lblSmall_Pic;
	protected global::System.Web.UI.WebControls.Label lblNews_Poster;
	protected global::System.Web.UI.WebControls.Label lblNews_Hits;
	protected global::System.Web.UI.WebControls.Label lblMsg_Counts;
	protected global::System.Web.UI.WebControls.Label lblLables;

    }
}
